#!/usr/bin/env python3
"""Expand each destination's FAQs from ~3 to 6 by patching in new Q&As."""
import json
from pathlib import Path

DATA = Path(__file__).parent.parent / "data" / "destinations.json"

EXTRA_FAQS = {
    "queenstown-with-kids": [
        {"q": "How many days do I need in Queenstown with kids?", "a": "3–4 days is a comfortable minimum. Day 1: Gondola and luge, lakefront walk, Queenstown Gardens. Day 2: Jet boat on the Shotover, afternoon swim at Frankton Beach. Day 3: Arrowtown day trip. Day 4: Queenstown Hill walk or adventure activity. If you have time, add a day for Wanaka (45 minutes away)."},
        {"q": "Is Queenstown worth visiting in winter with kids?", "a": "Absolutely, especially if your kids are old enough to ski (usually 3–4+ with ski school). Coronet Peak is 20 minutes from town and has a good learners' area. In winter the town is festive and far less crowded than summer. Non-skiing winter activities include the Gondola, luge (runs year-round), Underwater Observatory, and the many excellent restaurants. Accommodation is 20–30% cheaper than January."},
        {"q": "What is the drive from Queenstown to Milford Sound?", "a": "About 4.5–5 hours each way via Te Anau — it's a long day trip with kids. Most families do it as an overnight trip (stay in Te Anau) or book a fly-cruise-fly option (fly one way, cruise, fly back) to reduce driving. The road is spectacular but involves significant winding sections — plan for car sickness with younger kids."},
    ],
    "rotorua-family-guide": [
        {"q": "Is Rotorua smelly? Will kids complain?", "a": "Yes — Rotorua has a mild sulphur smell from the geothermal activity, especially in the CBD. Most kids find it funny rather than unpleasant, and you stop noticing it within a few hours. The smell is strongest near geothermal sites like Wai-O-Tapu and Hell's Gate. Hotels in the CBD can have it; those further out (e.g., near the lakes) are mostly smell-free."},
        {"q": "What age is best for the Māori cultural experiences in Rotorua?", "a": "Ages 5 and up enjoy most cultural experiences — the kapa haka (song and dance), hangi (earth oven meal), and Māori village tours at Te Puia and Tamaki are engaging for school-age kids. Under 5s can manage but may lose focus during longer performances. Te Puia also has the famous geysers and kiwi house which younger children enjoy."},
        {"q": "Can you visit Rotorua in one day from Auckland?", "a": "Yes — Rotorua is about 2.5 hours from Auckland. A day trip gives you enough time for Wai-O-Tapu or Te Puia, the Agrodome, and lunch. However, you'll be rushing. An overnight stay lets you do a Māori cultural evening (dinner + performance), adds Rainbow Springs and the luge, and is far less stressful. See our Rotorua day trip itinerary for a tight but doable day plan."},
    ],
    "taupo-with-kids": [
        {"q": "Is Huka Falls free to visit?", "a": "Yes — Huka Falls is completely free and one of the most spectacular sights in New Zealand. The car park is free, the walkway is flat and pram-friendly (300m to the viewing platform), and there are toilets on-site. It's the most-visited natural attraction in NZ for good reason — the volume and colour of the water is genuinely jaw-dropping."},
        {"q": "Can kids swim in Lake Taupo?", "a": "Yes — Lake Taupo is one of the best freshwater swimming lakes in NZ. The water is clean and clear, though cold (16–20°C in summer, much colder in winter). Acacia Bay on the western shore is sheltered and popular with families. The main town beach (Two Mile Bay) also has good swimming with a playground nearby. The lake is geothermally warmed very slightly but still cool."},
        {"q": "Is Taupo worth a full day or just a stop?", "a": "Taupo easily fills 2–3 days for families. Day 1: Huka Falls (free), Craters of the Moon walk, Taupo lakefront and beach. Day 2: Huka Jet boat, AC Baths hot pools, evening at the i-SITE foreshore. Day 3: Great Lake Trail cycling, Wairakei Thermal Valley, Aratiatia Rapids (check dam release times). It's also a natural halfway stop on the Rotorua–Wellington drive."},
    ],
    "christchurch-with-kids": [
        {"q": "Is the Antarctic Centre worth it for kids?", "a": "Yes — the International Antarctic Centre is one of the best paid attractions in NZ for families. The Hagglund all-terrain vehicle ride, the storm experience, the Little Blue penguins, and the interactive exhibits are all excellent. Budget 2.5–3 hours. Book online for a small discount. It's particularly good for rainy days and is right next to the airport, making it a perfect first or last activity."},
        {"q": "What is free to do in Christchurch with kids?", "a": "Several excellent free options: Botanic Gardens and punting (gondola is paid but the gardens are free), Canterbury Museum, Hagley Park, New Brighton beach and pier, the Avon River Precinct, and the Cardboard Cathedral (free to enter). The city centre is compact and very walkable. The free City Circuit bus connects most of the main attractions."},
        {"q": "How far is Christchurch from the ski fields?", "a": "Mt Hutt is the closest ski field — about 90 minutes from central Christchurch via Methven. It's a large, well-developed family resort with a good ski school for kids. Porters and Craigieburn are closer (60 minutes) but smaller and more suited to intermediate skiers. On the way to Mt Hutt, stop at Methven for gear hire — it's cheaper than buying equipment in Christchurch."},
    ],
    "bay-of-islands-family": [
        {"q": "What is the best base for Bay of Islands — Paihia or Russell?", "a": "Paihia is the main hub with most accommodation, restaurants, and tour operators — it's the easier choice for families. Russell is quieter, charming, and reached by ferry (5 min, $14 return for adults, kids free). Russell is worth a half-day visit regardless of where you stay — the Duke of Marlborough is NZ's oldest pub and the beach is lovely. Stay in Paihia for convenience, visit Russell for the character."},
        {"q": "Is the Hole in the Rock worth doing with young kids?", "a": "The Cape Brett cruise including the Hole in the Rock is a full-day trip (4–5 hours) and involves open water — check conditions before booking, as it can be rough. Kids 7+ usually manage well; younger children are hit-or-miss depending on sea conditions and temperament. The shorter Dolphin Discovery cruise (3 hours) is better for under-6s — more sheltered water and reliable dolphin encounters."},
        {"q": "What are the best beaches in Bay of Islands for families?", "a": "Waitangi Beach (in front of the Treaty Grounds, patrolled in summer), Paihia Beach (calm, sheltered, central), Haruru Falls reserve and beach (less known, beautiful), and across the water, Long Beach in Russell (one of the best family beaches in Northland). For something special, the offshore islands (Urupukapuka Island) have spectacular snorkelling — accessible by water taxi."},
    ],
    "wanaka-with-kids": [
        {"q": "Is Wanaka better than Queenstown for families?", "a": "For younger families (under 10), many parents prefer Wanaka — it's quieter, less commercial, and the lake and town centre are more relaxed. Cardrona ski resort is world-class for families in winter. Puzzling World is a genuine Wanaka institution. The lake is spectacular for swimming and kayaking in summer. Queenstown has more activities and more restaurant variety, but Wanaka has more soul and is less rushed."},
        {"q": "How far is Wanaka from Queenstown?", "a": "About 1 hour via the direct Crown Range Road (the highest sealed road in NZ — spectacular views but steep and winding, not suitable for campervans or in icy conditions). Via the main highway through Cromwell it's about 75 minutes. The Crown Range is worth doing in good conditions — the views from the top are extraordinary. Check conditions in winter before attempting it."},
        {"q": "What is the best time to visit Wanaka with kids?", "a": "Summer (Dec–Feb) for lake swimming, hiking, and outdoor activities — the town is busy but manageable. Autumn (March–May) for stunning golden colours around the lake, fewer crowds, and great hiking conditions. Winter (June–Sept) for Cardrona skiing — Wanaka is much quieter than Queenstown for ski families. Spring (Oct–Nov) is underrated — warming up, lake accessible, uncrowded. Avoid peak January if you hate queues."},
    ],
    "wellington-with-kids": [
        {"q": "Is Te Papa free for kids?", "a": "Yes — Te Papa Tongarewa (the national museum) is completely free for all visitors including children. It's world-class and easily fills 3–4 hours. The natural history exhibits, the Māori collection, and the earthquake simulator are all kid-friendly highlights. It's open daily and is one of the best free family activities in New Zealand, full stop."},
        {"q": "Is Wellington worth visiting with a young family?", "a": "Yes — Wellington has excellent family infrastructure. Te Papa is free and world-class. The cable car and Botanic Gardens are easy and scenic. Zealandia wildlife sanctuary is exceptional for native birds. The waterfront is flat, walkable, and has cafés and playgrounds. The only downside is Wellington's notorious wind — pack layers year-round. The compact city centre means you can cover a lot without much driving."},
        {"q": "How many days do we need in Wellington with kids?", "a": "Two full days is a comfortable minimum: Day 1 — Te Papa, waterfront, cable car, Botanic Gardens. Day 2 — Zealandia, Mt Victoria lookout (for older kids), Cuba Street for lunch, Weta Workshop tour (for movie fans 10+). A third day allows for day trips — the Wairarapa wine region is 1 hour away, or Kapiti Island (world-class bird sanctuary) if booked ahead."},
    ],
    "nelson-abel-tasman-family": [
        {"q": "Can you do the Abel Tasman in one day with kids?", "a": "Yes, with the right planning. The most popular family option is a half-day water taxi + walk combination: taxi to Anchorage or Bark Bay, walk 2–3 hours of the track, return by taxi. This avoids the full multi-day hike but gives you the coastal scenery and golden sand beaches. Book the water taxi ahead — Abel Tasman Water Taxis depart from Marahau. The kayak hire companies also do guided half-day options."},
        {"q": "When is the best time to visit Nelson with kids?", "a": "Nelson is the sunniest city in New Zealand — it averages 2400+ sunshine hours per year. Summer (Dec–Feb) is peak for Abel Tasman, beach swimming at Tahunanui, and outdoor markets. Autumn (March–May) is excellent with settled weather and fewer people. Winter is mild and pleasant for the region (14–16°C average), making it one of NZ's best off-season destinations. Avoid Abel Tasman track in July–August if you want reliable dry conditions."},
        {"q": "What are the best free activities in Nelson with kids?", "a": "Tahunanui Beach (patrolled in summer, playground, holiday park right on the beach), the Centre of New Zealand walk (short, 30 min return, great views), World of WearableArt Museum gardens (free outside), Nelson Saturday Market, and the Maitai Valley walks. For older kids, the Dun Mountain trail is accessible by mountain bike. The Hoglund Art Glass gallery is free and kids find the glass-blowing fascinating."},
    ],
    "coromandel-with-kids": [
        {"q": "How far is Hot Water Beach from Auckland?", "a": "About 2.5 hours from Auckland via the main state highway, or 3 hours if you take the more scenic Coromandel Town route. It's achievable as a long day trip but overnight is much better — you can dig your hot pool at the optimal low tide time (check tide times before you go — the beach only works within 2 hours either side of low tide). The Coromandel Peninsula is most enjoyable as a 2–3 night trip."},
        {"q": "Is Cathedral Cove walkable with kids?", "a": "The Cathedral Cove walkway is 3.2km return from the Hahei car park, taking about 1.5 hours return with young kids. The track is well-formed but hilly in places — doable for most kids 5+ with patience. During peak summer (Christmas to late January), cars can't park at the trailhead and a shuttle runs from Hahei. Alternatively, take a water taxi from Hahei (10 minutes) to arrive directly at the cove — far easier with under-5s."},
        {"q": "What is there to do in Coromandel besides Hot Water Beach and Cathedral Cove?", "a": "Quite a lot: the Coromandel Walkway (if your kids are older, 7km point-to-point), Driving Creek Railway (a narrow-gauge scenic railway — excellent for kids of all ages), Thames Goldmine experience, kayaking from Hahei or Whangamata, and Whangapoua Beach (one of the most beautiful and least-visited beaches on the peninsula). The whole peninsula has excellent fish and chips at local takeaways — a NZ coastal tradition."},
    ],
    "fiordland-milford-sound-family": [
        {"q": "Is Milford Sound worth the drive with kids?", "a": "Yes — Milford Sound is one of those places that lives up to the hype even with tired kids in the car. The 2-hour drive from Te Anau through the Homer Tunnel is itself spectacular. A 2-hour boat cruise lets you see Mitre Peak, Bowen Falls, and seals. The whole experience (drive in, cruise, drive out) takes a full day from Te Anau. Stay in Te Anau the night before to avoid a very early start. The Milford Road is one of NZ's most scenic drives."},
        {"q": "What is the best cruise option for families in Milford Sound?", "a": "For families, the 2-hour cruise is the standard choice — long enough to see everything without kids losing interest. Real Journeys and Go Orange both run family-friendly cruises with indoor heated lounges. If seasickness is a concern, choose a larger vessel — the catamaran-style boats are more stable than smaller vessels. Underwater Observatory cruises also visit the unique marine observation chamber — a bonus activity worth adding."},
        {"q": "Can I drive to Milford Sound in a campervan?", "a": "Yes, but check your campervan rental terms — some companies restrict driving through the Homer Tunnel. The road is sealed all the way and campervans are common. There is a basic DOC campsite at Milford Sound itself (book ahead — it fills fast in summer) and better facilities at Te Anau. Do not attempt the Milford Road in heavy snow or ice without chains. Road conditions are available at the NZTA website."},
    ],
    "northland-cape-reinga-family": [
        {"q": "How do I get to Cape Reinga with kids?", "a": "Most families take a day tour from Paihia or Kaitaia — these typically include Cape Reinga, 90 Mile Beach (including optional sandboarding), and a stop at Te Paki Stream. Self-driving is possible in a regular car (Cape Reinga Road is sealed), but 90 Mile Beach is not recommended for regular vehicles — it's tidal and you can get bogged. Allow a full day from Paihia (7–8 hours total)."},
        {"q": "Is sandboarding at Te Paki worth it for kids?", "a": "Absolutely — Te Paki Stream sand dunes are a highlight that most kids rate as the best thing of the whole holiday. The dunes are massive (150m high) and you can bodyboard down on boogie boards provided by tour operators, or bring your own. The climb up is hard work in soft sand (15–20 min) but the descent is 20 seconds of pure joy. Even most 4-year-olds manage the climb with encouragement. Wear clothes you don't mind getting sandy."},
        {"q": "What else is there to do in Northland besides Cape Reinga?", "a": "Northland is underrated beyond Cape Reinga. The Bay of Islands is the main hub (Waitangi Treaty Grounds, dolphin cruises, Russell village). Whangarei has the Town Basin, Whangarei Falls (one of NZ's most accessible waterfalls), and the Hundertwasser Art Centre. The Hokianga Harbour and giant kauri trees at Waipoua Forest (including Tāne Mahuta, NZ's largest living kauri) are genuinely special and accessible for all ages."},
    ],
    "tauranga-mount-maunganui-family": [
        {"q": "Is Mount Maunganui beach safe for young swimmers?", "a": "Yes — the main Mount Maunganui beach (Main Beach) is one of the safest patrolled beaches in the Bay of Plenty, with Surf Life Saving patrols operating in summer. The surf is generally moderate and the beach shelves gradually. Pilot Bay (the harbour side of the Mount) is calmer still — ideal for toddlers and non-swimmers. The Mount Hot Pools are also family-friendly with a shallow pool area for younger children."},
        {"q": "Can you climb Mount Maunganui with kids?", "a": "Yes — the Mauao base track (flat, 3.4km around the base) is suitable for all ages and prams. The summit walk (45 min return, steep in parts) is achievable for kids 6+ who are reasonably fit. Views from the top are excellent — the Bay of Plenty coastline is spectacular on a clear day. Start early in summer to avoid the heat. The base track through the reserve passes native bush with tūī and kererū (wood pigeons)."},
        {"q": "What is the drive time from Auckland to Tauranga?", "a": "About 2.5–3 hours from Auckland via the Kaimais (SH2). The main pass road is steep and winding in places — take it slowly with young passengers. Via Hamilton (SH1 then SH29) is about the same time and flatter. Tauranga is best combined with a Coromandel Peninsula trip — you can do a loop: Auckland → Coromandel → Whitianga → Tauranga → Rotorua → Auckland in a 5–7 day road trip."},
    ],
    "hawkes-bay-family-guide": [
        {"q": "Is Hawke's Bay worth visiting with kids who aren't into wine?", "a": "Yes — Hawke's Bay has more to offer families than just wine. Cape Kidnappers (gannet colony) is one of the most spectacular wildlife experiences in NZ. Napier's Art Deco city centre is unique and walkable. Ocean Beach is patrolled in summer and excellent. Te Mata Peak has easy walks and great views. The region is sunnier than most of NZ and the food scene is exceptional. Budget: lower than Queenstown or Rotorua."},
        {"q": "What is Cape Kidnappers and is it suitable for kids?", "a": "Cape Kidnappers is home to one of the world's largest accessible gannet colonies — thousands of birds nest on the clifftops from October to April. You can walk (9km return from the beach car park — suitable for kids 8+ who can manage a long walk) or take a tractor tour (much easier, departs from the Gannet Beach Adventures base). The tractor tour is the family-friendly option — book ahead as it's very popular. Not accessible in winter when gannets have migrated."},
        {"q": "What is the best beach in Hawke's Bay for families?", "a": "Ocean Beach (south of Napier) is the most popular family beach — patrolled in summer, good surf for bodyboarding, and a café nearby. Westshore Beach in Napier is very calm and suits toddlers and non-swimmers. Waimarama Beach (40 min south of Napier) is one of the most beautiful white-sand beaches in the region, uncrowded outside school holidays. The bay area has excellent rock pooling at low tide for younger explorers."},
    ],
    "dunedin-family-guide": [
        {"q": "Is Dunedin worth visiting with kids?", "a": "Yes — Dunedin is genuinely underrated for families. The Royal Albatross Centre at Taiaroa Head is world-class (only mainland royal albatross colony in the world). The Otago Peninsula wildlife — sea lions, little blue penguins, fur seals — is incredible for kids. Dunedin's Victorian architecture and the famous Baldwin Street (world's steepest street) are quirky attractions. The Otago Settlers Museum and Dunedin Railway Station are both worth a visit."},
        {"q": "What is the Otago Peninsula and is it worth the drive?", "a": "The Otago Peninsula is a 30km scenic drive from Dunedin — absolutely worth it with kids. Wildlife highlights: royal albatrosses at Taiaroa Head (book the tour at the visitor centre), sea lions at Allans Beach (free, walk along the beach and they're often right there), and little blue penguins at Pilots Beach at dusk (free, return to shore just after sunset — spectacular). Allow a full day for the peninsula."},
        {"q": "How many days do we need in Dunedin?", "a": "Two days minimum: Day 1 — Dunedin city (Railway Station, Speight's Brewery tour for adults, Otago Museum, Baldwin Street), Day 2 — Otago Peninsula full day (albatrosses, sea lions, penguins at dusk). A third day can include a train trip on the Taieri Gorge Railway (one of NZ's most spectacular rail journeys, 4.5 hours return) or a day trip to Moeraki Boulders (90 min north — remarkable spherical rocks on the beach)."},
    ],
    "auckland-with-kids": [
        {"q": "How many days do we need in Auckland?", "a": "Two to three days covers the main city attractions comfortably. Day 1: Auckland Museum (free for NZ residents; fee for international visitors), Cornwall Park, One Tree Hill walk. Day 2: Kelly Tarlton's Sea Life Aquarium, Mission Bay beach, Tamaki Drive drive. Day 3: Auckland Zoo or Rainbow's End, Devonport ferry trip. If you want to include Waiheke Island or Rangitoto, add another day."},
        {"q": "Is Waiheke Island worth the ferry with kids?", "a": "Yes — Waiheke is 35 minutes by ferry from the CBD and one of the best day trips from Auckland for families. The island has beautiful beaches (Oneroa, Palm Beach), good cycling on e-bikes, excellent cafés, and stunning views. The ferry itself is part of the experience — kids love it. Best in summer when swimming is the goal. The main drag in Oneroa village has good food options. Book return ferries ahead in summer as they fill up."},
    ],
    "new-plymouth-taranaki-family": [
        {"q": "Is the Len Lye Centre worth visiting with kids?", "a": "The Len Lye Centre within the Govett-Brewster Art Gallery houses kinetic sculptures that literally move and make sound — genuinely fascinating for kids of all ages and most adults. Entry is free. Allow 1–1.5 hours. Combine it with the Pukekura Park and Brooklands Zoo which are adjacent and also free — the park has a lake with paddleboats and a fantastic children's playground."},
        {"q": "What is the Coastal Walkway in New Plymouth?", "a": "The New Plymouth Coastal Walkway is a 13km paved path along the Taranaki coast from Fitzroy to Bell Block — one of the best urban coastal paths in NZ. Families typically do a section rather than the whole thing. The Wind Wand (a Len Lye sculpture) near the Len Lye Centre is a highlight. The walkway is flat, wide, and suitable for bikes, scooters, and prams. The section from New Plymouth CBD to Fitzroy Beach takes about 45 minutes walking."},
        {"q": "Is Mt Taranaki accessible with children?", "a": "The lower walks around Mt Taranaki (Egmont National Park) are accessible and rewarding for families. The Enchanted Walk (30 min loop), Wilkies Pools Track (1.5 hr return to beautiful rock pools), and Kamahi Loop (1 hr) are all suitable for kids 5+. The summit is a serious mountaineering objective — do not attempt with children. Even partial ascents above the bushline require experience and equipment. Stick to the lower tracks for an excellent family experience."},
    ],
    "marlborough-blenheim-family": [
        {"q": "What is there to do in Marlborough with kids (not wine)?", "a": "Quite a lot — Marlborough is underrated for families beyond wine. The Marlborough Sounds by boat or kayak are spectacular (Queen Charlotte Track water taxi day trips are excellent). Havelock is the 'Greenshell Mussel Capital' — the mussel chowder at the Havelock Restaurant is worth a detour. Lake Elterwater is a quiet gem for swimming. Blenheim has the Omaka Aviation Heritage Centre (jaw-dropping WW1 aircraft — kids love it) and a good splash pad in town."},
        {"q": "How far is Marlborough from Christchurch and from Wellington?", "a": "Marlborough (Blenheim) is about 1.5 hours south of Picton via the Queen Charlotte Drive or SH6 — beautiful coastal drive. Wellington to Picton by Interislander ferry is 3.5 hours (book ahead in summer). Christchurch is about 3.5 hours south of Blenheim via SH1 — a manageable drive with kids if you break it up at Kaikōura (whale watching, seal colony at the peninsula — worth a stop). Marlborough is ideal as a first or last stop on a South Island road trip from the ferry."},
        {"q": "When should we visit the Marlborough Sounds?", "a": "Summer (Dec–Feb) for swimming, kayaking, and walking the Queen Charlotte Track in good conditions. Autumn (March–May) is excellent with settled weather and golden vineyards — beautiful and much quieter. Winter is mild here (Marlborough is sheltered and sunny for much of the year) and the Sounds are dramatic and uncrowded. Spring (Sept–Nov) is excellent timing before the summer crowds arrive."},
    ],
    "west-coast-family-guide": [
        {"q": "Is the Pancake Rocks worth the stop with kids?", "a": "Absolutely — Punakaiki's Pancake Rocks and Blowholes are one of the most dramatic natural sights in NZ and the walkway is easy (20 min loop, fully paved, pram-accessible). When the swell is right, the blowholes are spectacular — check the blowhole activity schedule at the visitor centre (high swell + incoming tide is optimal). It's a perfect leg-stretch stop on the West Coast drive — allow 45 minutes including the walk."},
        {"q": "Can you see the Franz Josef and Fox glaciers with kids?", "a": "The glacier terminals are not accessible on foot due to ongoing glacier retreat and rockfall risk — guided heli-hikes are the only way onto the glaciers themselves, starting from around $350/person (no minimum age but operators set their own limits — usually 8+ for heli-hike). However, the valley walks to the glacier viewpoints are free, scenic, and suitable for all ages. Franz Josef village also has the West Coast Wildlife Centre (kiwi and tuatara — excellent for kids, $35 adults)."},
        {"q": "What is the drive like along the West Coast with kids?", "a": "The West Coast main highway (SH6) is one of NZ's most scenic drives — stunning coastal rainforest, mountains, and wild beaches. However, it's a long drive: Greymouth to Franz Josef is 2.5 hours, Franz Josef to Haast Pass is another 2.5 hours. Plan for frequent stops and be aware that the road has limited fuel and food options between towns — fill up in Hokitika, Greymouth, and Franz Josef before remote sections. Cellphone coverage is patchy throughout."},
    ],
    "gisborne-east-cape-family": [
        {"q": "Is the East Cape drive suitable for families?", "a": "Yes — the East Cape circuit (SH35 from Gisborne around the cape) is one of NZ's great undiscovered road trips. The full circuit is about 330km and takes 5–6 hours driving (plan for a full day with stops). Highlights: Te Araroa (the pohutukawa tree at the beach — the oldest in NZ), Hicks Bay, and East Cape Lighthouse (the most easterly lighthouse in NZ, 700 steps up — great for kids who like a climb). Gisborne itself has excellent beaches and is the first city to see the sunrise on New Year's Day."},
        {"q": "What are the best beaches in Gisborne for families?", "a": "Midway Beach (right in Gisborne city, patrolled in summer, excellent surf for bodyboarding), Wainui Beach (20 min north, large and less crowded), and Makorori (small, sheltered cove, excellent for swimming). Gisborne's beaches are among the least crowded in NZ — even in peak summer they're relaxed. The beach water warms up quickly here as Gisborne is the easternmost major city — swimming season starts earlier and ends later than most NZ cities."},
        {"q": "Is Gisborne worth visiting as a detour?", "a": "Gisborne is genuinely off the main tourist circuit but rewards visitors who make the effort. Key selling points for families: excellent uncrowded beaches, the Tairawhiti Museum (free, good Māori and settler history), nearby Morere Hot Springs (natural thermal pools in native bush — excellent), and the East Cape drive. It's about 5.5 hours from Auckland via Rotorua or 6 hours from Wellington via Napier — position it as a destination rather than a quick stop."},
    ],
}

def main():
    destinations = json.loads(DATA.read_text())
    changed = 0
    for dest in destinations:
        slug = dest["slug"]
        extra = EXTRA_FAQS.get(slug, [])
        if extra:
            dest["faqs"] = dest.get("faqs", []) + extra
            changed += 1
            print(f"  {dest['name']}: {len(dest['faqs'])} FAQs total")
    DATA.write_text(json.dumps(destinations, indent=2, ensure_ascii=False))
    print(f"\nUpdated {changed} destinations.")

if __name__ == "__main__":
    main()
